server {
    #Pre LetsEncrypt SSL configuration
    listen 80;
    server_name spletka.com www.spletka.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 200 'ready';
        add_header Content-Type text/plain;
    }
}
