server {
    listen 80;
    server_name localhost;

    location / {
        rewrite ^ /600/400 break;
        proxy_pass https://picsum.photos;
        proxy_ssl_server_name on;
        proxy_set_header Host picsum.photos;

        proxy_intercept_errors on;
        error_page 500 502 503 504 = @fallback;
    }

    location @fallback {
        try_files /placeholder.svg =404;
    }
}